name: build-deploy
on: push

env:
  TEAM_NAME: omicron
  PROJECT_NAME: simple-sqsd
  AWS_DEFAULT_REGION: us-east-1

jobs:
  check-build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ECR_REGISTRY: "${{ steps.login-ecr.outputs.registry }}"
        run: |
          docker build -t simple-sqsd .
          docker tag simple-sqsd:latest 165918379116.dkr.ecr.us-east-1.amazonaws.com/simple-sqsd:latest
          docker push 165918379116.dkr.ecr.us-east-1.amazonaws.com/simple-sqsd:latest
